###
 #GET http://localhost:5000/articles

#get all
 #GET http://localhost:5000/articles

#get by name
GET http://localhost:5000/articles/Articol123


#post an article
POST http://localhost:5000/articles
Content-Type: : application/json

{
    "Article_name": "Articsafaol ceva",
    "Article_no": "221",
    "Article_short_description": "Ceva articol"
}



